Repository devind-team/dcis, pull requests merged in 2022-08, with the labels that each got.

#617 Исправлен баг при удалении проекта и периода
  client/pages/dcis/periods/_periodId/settings.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/_projectId/settings.vue
  client/pages/dcis/projects/index.vue
Labels: bug, javascript

#618 Удалены пользователи
  client/pages/panel/ac.vue
  client/pages/panel/ac/groups.vue
  client/pages/panel/ac/index.vue
  client/pages/panel/ac/users.vue
  server/apps/core/fixtures/User.json
Labels: invalid, javascript, python

#632 Поправлена форма добавления проекта
  client/components/dcis/projects/AddProject.vue
Labels: invalid, javascript

#633 Убрано избыточное дублирование названия учреждения
  client/pages/dcis/documents/_documentId.vue
Labels: invalid, javascript

#634 Исправлено дублирование, а также добавлен пользователь к документу
  docs/docs/document_rules.md
  server/apps/dcis/migrations/0021_add_document_user.py
  server/apps/dcis/models/document.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/services/project_services.py
  server/apps/dcis/tests/services/document_services.py
Labels: bug, invalid, javascript, python

#635 Отделены представители учреждений от других пользователей
  client/components/common/forms/MutationForm.vue
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/documents/AddDocument.vue
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/dcis/documents/DocumentStatusesReadonly.vue
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/gql/dcis/fragments/status_fields.graphql
  client/gql/dcis/queries/document.graphql
  client/gql/dcis/queries/documents.graphql
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/dcis/migrations/0022_protected_status.py
  server/apps/dcis/models/document.py
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/permissions/project_permissions.py
  server/apps/dcis/permissions/value_permissions.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/tests/permissions/document_permissions.py
  server/apps/dcis/tests/permissions/period_permissions.py
  server/apps/dcis/tests/permissions/project_permissions.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/document_services.py
  server/apps/dcis/tests/values/__init__.py
Labels: feature, javascript, python

#637 Сделан форматированный вывод числовых значений
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellNumeric.vue
  client/composables/grid.ts
  client/gql/dcis/mutations/document/add_document.graphql
  client/lang/ru/dcis.ts
  client/types/graphql.d.ts
Labels: feature, javascript

#639 Исправлены разрешения
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/gql/dcis/queries/document_sheet.graphql
  client/gql/dcis/queries/documents_sheet.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/sheet_unload_services.py
Labels: invalid, javascript, python

#660 Cделано скрытие проекта
  docs/docs/document_rules.md
  server/apps/dcis/services/project_services.py
  server/apps/dcis/tests/permissions/document_permissions.py
  server/apps/dcis/tests/services/project_services.py
Labels: invalid, python

#659 Исправлено название поля
  client/lang/ru/dcis.ts
Labels: invalid, javascript

#658 Выведены все разрешения
  client/components/dcis/periods/PeriodGroupPrivileges.vue
Labels: bug, javascript

#663 Исправлена ошибка при добавлении периода
  server/apps/dcis/helpers/cell.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/excel_extractor_services.py
Labels: bug, python

#664 Сделано редактирование readonly для ячейки
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/projects/AddPeriod.vue
  client/composables/grid-mutations.ts
  client/gql/dcis/mutations/period/add_period.graphql
  client/lang/ru/dcis.ts
  client/schema.graphql
  client/services/grid.ts
  client/types/graphql.d.ts
  client/types/grid.ts
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/services/sheet_services.py
Labels: feature, javascript, python

#674 Авторизованный пользователь всегда попадает на проекты
  client/package.json
  client/pages/index.vue
  client/yarn.lock
  server/poetry.lock
Labels: feature, javascript

#675 Убрана возможность изменения информации, которая забирается с портала
  client/components/profile/BasicInformation.vue
  client/pages/profile/me.vue
Labels: enhancement, javascript

#676 Поправлена переадресация на сервер авторизации
  client/middleware/redirect-auth.ts
  client/pages/auth/login.vue
  client/pages/auth/logout.vue
  client/pages/index.vue
  client/stores/auth-store.ts
  server/poetry.lock
Labels: bug, enhancement, javascript, python

#673 672 flake8 для сервера
  .github/lint_pull_request.yml
  server/generate_docs.py
Labels: github_actions

#691 682 Покрытие тестами document_services.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/tests/services/document_services.py
Labels: python

#671 670 запуск тестов на сервере
  .github/workflows/build.yml
  .github/workflows/pull_request.yml
Labels: github_actions

#715 Добавлена дата последнего редактирования документа
  client/components/global/ThemeColor.vue
  client/lang/ru/dcis.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/dcis/periods/_periodId/documents.vue
  client/pages/profile.vue
  client/pages/profile/me.vue
  client/yarn.lock
  server/apps/dcis/models/document.py
  server/apps/dcis/schema/mutations/value_mutations.py
  server/apps/dcis/services/value_services.py
Labels: feature

#716 Добавление установки фильтра по умолчанию
  client/components/common/filters/ItemsDataFilter.vue
  client/nuxt.config.ts
  client/pages/dcis/projects/index.vue
Labels: feature

#717 Убраны предупреждения при ожидании оптимистического ответа
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridSheets.vue
  client/composables/grid-mutations.ts
  client/gql/dcis/mutations/values/change_value.graphql
Labels: bug
