Repository devind-team/dcis, pull requests merged in 2022-09, with the labels that each got.

#735 Импорт дивизионов из файла
  client/components/dcis/periods/AddPeriodDivisions.vue
  client/components/dcis/periods/AddPeriodDivisionsFromFile.vue
  client/components/dcis/periods/AddPeriodDivisionsMenu.vue
  client/components/dcis/periods/AddPeriodGroup.vue
  client/components/dcis/periods/AddPeriodUser.vue
  client/components/dcis/periods/CopyPeriodGroups.vue
  client/gql/dcis/mutations/period/add_divisions_from_file.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/divisions.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_services.py
Labels: enhancement, feature

#744 Импорт дивизионов из предыдущих периодов
  client/.eslintrc.js
  client/components/dcis/periods/AddPeriodDivisionsFromFile.vue
  client/components/dcis/periods/AddPeriodDivisionsFromPeriod.vue
  client/components/dcis/periods/AddPeriodDivisionsMenu.vue
  client/gql/dcis/mutations/period/add_divisions_form_period.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId/divisions.vue
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/types/graphql.d.ts
  client/yarn.lock
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_services.py
Labels: feature, javascript, python

#756 Добавлены запросы для интеграции с порталом
  server/.env.example
  server/apps/core/middleware/database_requests_middleware.py
  server/apps/core/serializers.py
  server/apps/dcis/filters.py
  server/apps/dcis/middleware/__init__.py
  server/apps/dcis/middleware/external_token_middleware.py
  server/apps/dcis/serializers.py
  server/apps/dcis/urls.py
  server/apps/dcis/views.py
  server/devind/settings.py
  server/devind/swagger.py
  server/devind/urls.py
  server/external.http
  server/poetry.lock
  server/pyproject.toml
Labels: feature, python

#757 Скрыт тулбар для режима редактирования документа
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/GridSheets.vue
  client/components/global/AppBar.vue
  client/middleware/redirect-auth.ts
Labels: invalid, javascript

#758 Улучшен поиск дивизионов
  client/components/dcis/periods/AddPeriodDivisions.vue
  server/apps/dcis/services/divisions_services.py
Labels: invalid, feature, python

#760 Исправлен баг при переадресации с главной страницы
  client/pages/index.vue
Labels: bug

#767 Некоторые косметические правки
  client/components/dcis/grid/GridSheetToolbar.vue
  client/composables/filters.ts
  client/pages/index.vue
  client/pages/panel/ac.vue
  client/pages/panel/ac/groups.vue
  client/pages/panel/ac/index.vue
  client/pages/panel/ac/users.vue
Labels: bug, feature

#768 Исправлена ошибка добавления периода
  server/apps/dcis/services/excel_extractor_services.py
Labels: bug

#769 Сделано отображение ошибок в формулах
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridHeader.vue
  server/apps/dcis/helpers/cell.py
Labels: bug, enhancement, javascript, python

#765 Написаны тесты для period_services.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/resources/test_create_period.xlsx
  server/apps/dcis/tests/services/period_services.py
  server/poetry.lock
  server/pyproject.toml
Labels: python

#773 Исправлена проблема с фиксацией строк и столбцов при наличии ячеек с rowspan
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/composables/grid.ts
  client/types/grid.ts
Labels: bug, javascript

#788 Написать джанго команду для фикстур
  readme.md
  server/apps/core/fixtures/001_User.json
  server/apps/core/fixtures/002_Setting.json
  server/apps/core/fixtures/003_Profile.json
  server/apps/core/fixtures/004_ProfileValue.json
  server/apps/core/fixtures/005_Application.json
  server/apps/core/fixtures/006_Privilege.json
  server/apps/core/fixtures/007_Status.json
  server/apps/core/fixtures/008_Department.json
  server/apps/core/fixtures/009_Project.json
  server/apps/core/fixtures/010_Period.json
  server/apps/core/fixtures/011_PeriodGroup.json
  server/apps/core/fixtures/Department.json
  server/apps/core/fixtures/PeriodGroup.json
  server/apps/core/fixtures/ProfileValue.json
  server/apps/core/management/commands/load_fixtures.py
  server/apps/pages/fixtures/001_Language.json
  server/apps/pages/fixtures/002_Category.json
  server/apps/pages/fixtures/003_PageKind.json
Labels: feature, python

#793 Поправлена нумерация строк и столбцов
  server/apps/dcis/services/excel_extractor_services.py
Labels: bug, python

#789 Cделан фильтр документов по статусу
  client/components/common/filters/ItemsDataFilter.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/documents.vue
Labels: feature, javascript

#798 Изменен фон у ячеек readonly
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
Labels: feature, javascript

#800 Поправлен фильтр дивизионов
  client/pages/dcis/periods/_periodId/documents.vue
Labels: bug

#819 Улучшена фильтрация документов
  client/gql/dcis/queries/documents.graphql
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/services/grapqhl/queries/dcis/documents.ts
  client/types/graphql.d.ts
  server/apps/dcis/filters.py
  server/apps/dcis/models/document.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/tests/services/document_services.py
  server/apps/dcis/views.py
Labels: feature, javascript, python

#830 Исправлен пропуск значений с 0
  server/apps/dcis/services/add_document_data_services.py
Labels: bug

#831 Форматированный вывод для типа ячейки текст
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellText.vue
  server/apps/dcis/services/excel_extractor_services.py
Labels: bug, javascript

#833 Уменьшена ширина баннера на 12% экрана
  client/components/dcis/ui/WaveContainer.vue
Labels: wontfix

#872 849 добавить галочку о том можно ли создавать множество версий
  client/components/dcis/documents/AddDocument.vue
  client/components/dcis/projects/AddPeriod.vue
  client/gql/dcis/fragments/period_fields.graphql
  client/gql/dcis/mutations/period/add_period.graphql
  client/gql/dcis/mutations/period/change_period.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/settings.vue
  client/schema.graphql
  client/types/graphql.d.ts
  client/yarn.lock
  server/apps/dcis/migrations/0025_period_versioning.py
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/add_document_data_services.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/services/document_services.py
Labels: feature, javascript, python
