Repository devind-team/dcis, pull requests merged in 2022-10, with the labels that each got.

#887 chore: Удалён баннер
  client/pages/dcis/projects/index.vue
Labels: documentation

#896 В единичном типе сбора сделан переход по версии
  client/pages/dcis/periods/_periodId/documents.vue
Labels: bug, javascript

#910 Форматирование текстового поля
  client/components/dcis/attributes/AttributesValuesTabItem.vue
  client/components/dcis/periods/AddPeriodDivisionsFromPeriod.vue
  client/composables/grid-mutations.ts
  client/layouts/default.vue
  client/pages/dcis.vue
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/index.vue
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/divisions.vue
  client/pages/dcis/projects.vue
  client/pages/dcis/projects/_projectId/index.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/_projectId/settings.vue
  client/pages/dcis/projects/index.vue
  client/pages/profile.vue
  client/pages/profile/me.vue
  client/services/grapqhl/queries/dcis/periods.ts
  server/apps/dcis/apps.py
  server/apps/dcis/migrations/0029_cell_is_template.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/attribute_service.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/signals.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, feature

#922 Ограничение вывода организаций и их филиалов
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/projects/index.vue
  docker-compose.yml
  server/apps/dcis/helpers/exceptions.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/document_services.py
Labels: feature

#920 Вывод словарей с привилегиями
  client/components/dcis/dictionaries/UniversalDictionary.vue
  client/lang/en/dictionaries.ts
  client/lang/ru/dictionaries.ts
  client/pages/dcis/dictionaries.vue
  client/pages/dcis/dictionaries/budget_classifications.vue
  client/pages/dcis/dictionaries/departments.vue
  client/pages/dcis/dictionaries/organizations.vue
  client/pages/dcis/dictionaries/privileges.vue
Labels: enhancement, feature, javascript

#950 Кураторы
  .editorconfig
  client/components/common/forms/MutationForm.vue
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/curators/AddCuratorGroupMenu.vue
  client/components/dcis/curators/ChangeCuratorGroupUsers.vue
  client/components/dcis/projects/AddProject.vue
  client/components/users/AvatarDialog.vue
  client/gql/dcis/mutations/curator/add_curator_group.graphql
  client/gql/dcis/mutations/curator/add_users_curator_group.graphql
  client/gql/dcis/mutations/curator/delete_curator_group.graphql
  client/gql/dcis/mutations/curator/delete_user_curator_group.graphql
  client/gql/dcis/queries/curator_group_new_users.graphql
  client/gql/dcis/queries/curator_group_users.graphql
  client/gql/dcis/queries/curator_groups.graphql
  client/lang/en.ts
  client/lang/en/curators.ts
  client/lang/ru.ts
  client/lang/ru/curators.ts
  client/pages/panel/ac.vue
  client/pages/panel/ac/curator_groups.vue
  client/pages/panel/index.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  server/apps/dcis/management/commands/load_curator.py
  server/apps/dcis/migrations/0030_add_curator_group.py
  server/apps/dcis/migrations/0031_aggregation.py
  server/apps/dcis/models/__init__.py
  server/apps/dcis/models/curator.py
  server/apps/dcis/permissions/curator_permissions.py
  server/apps/dcis/schema/__init__.py
  server/apps/dcis/schema/mutations/__init__.py
  server/apps/dcis/schema/mutations/curator_mutation.py
  server/apps/dcis/schema/queries/__init__.py
  server/apps/dcis/schema/queries/curator_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/curator_services.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/curator_services.py
Labels: feature
