Repository devind-team/dcis, pull requests merged in 2022-07, with the labels that each got.

#483 Написана мутация для изменения значений ячейки
  client/components/dcis/grid/GridCell.vue
  client/composables/grid-mutations.ts
  client/gql/dcis/fragments/value_fields.graphql
  client/gql/dcis/mutations/sheet/add_row_dimension.graphql
  client/gql/dcis/mutations/sheet/change_value.graphql
  client/gql/dcis/mutations/sheet/unload_file_value_archive.graphql
  client/gql/dcis/mutations/values/change_file_value.graphql
  client/gql/dcis/mutations/values/change_value.graphql
  client/gql/dcis/queries/sheet.graphql
  client/gql/dcis/queries/value_files.graphql
  client/package.json
  client/pages/dcis/documents/_documentId.vue
  client/schema.graphql
  client/types/graphql.d.ts
  client/yarn.lock
  docs/evaluate.md
  readme.md
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/sheet_permissions.py
  server/apps/dcis/permissions/value_permissions.py
  server/apps/dcis/schema/__init__.py
  server/apps/dcis/schema/mutations/__init__.py
  server/apps/dcis/schema/mutations/cell_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/mutations/value_mutations.py
  server/apps/dcis/schema/queries/sheet_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/services/value_services.py
  server/docs/Makefile
  server/docs/conf.py
  server/docs/devind.rst
  server/docs/index.rst
  server/docs/make.bat
  server/poetry.lock
  server/pyproject.toml
Labels: dependencies, javascript, python

#495 Переделаны seed в fixtures
  server/apps/core/fixtures/Application.json
  server/apps/core/fixtures/Department.json
  server/apps/core/fixtures/PeriodGroup.json
  server/apps/core/fixtures/Privilege.json
  server/apps/core/fixtures/Profile.json
  server/apps/core/fixtures/ProfileValue.json
  server/apps/core/fixtures/Setting.json
  server/apps/core/fixtures/Status.json
  server/apps/core/fixtures/User.json
  server/apps/core/management/seed/001.core/001.User.json
  server/apps/core/management/seed/002.devind_core/002.Setting.json
  server/apps/core/management/seed/002.devind_core/003.Profile.json
  server/apps/core/management/seed/002.devind_core/004.ProfileValue.json
  server/apps/core/management/seed/003.devind_dictionaries/005.Department.json
  server/apps/core/management/seed/004.oauth2_provider/001.Application.json
  server/apps/core/management/seed/005.dcis/001.Privilege.json
  server/apps/core/management/seed/005.dcis/002.PeriodGroup.json
  server/apps/core/management/seed/005.dcis/003.Status.json
  server/apps/pages/fixtures/Category.json
  server/apps/pages/fixtures/Language.json
  server/apps/pages/fixtures/PageKind.json
  server/apps/pages/management/seed/001.pages/001.Language.json
  server/apps/pages/management/seed/001.pages/002.Category.json
  server/apps/pages/management/seed/001.pages/003.PageKind.json
Labels: refactoring

#516 Исправлено несоответствие расчетов сложных зависимостей при загрузке
  client/components/dcis/documents/AddDocument.vue
  client/composables/grid-mutations.ts
  client/gql/dcis/mutations/sheet/add_row_dimension.graphql
  client/gql/dcis/mutations/sheet/unload_file_value_archive.graphql
  client/gql/dcis/mutations/values/change_file_value.graphql
  client/gql/dcis/mutations/values/change_value.graphql
  client/gql/dcis/queries/sheet.graphql
  client/gql/dcis/queries/value_files.graphql
  client/plugins/README.md
  client/plugins/apollo.ts
  client/schema.graphql
  client/types/graphql.d.ts
  docs/evaluate.md
  docs/recalculate_cells.md
  server/apps/dcis/helpers/cell.py
  server/apps/dcis/helpers/sheet_cache.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/value_permissions.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/mutations/value_mutations.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/value_services.py
  server/apps/dcis/tests/helpers/__init__.py
  server/apps/dcis/tests/helpers/cell_helpers.py
  server/apps/dcis/tests/services/values_services.py
  server/apps/dcis/tests/values/__init__.py
  server/poetry.lock
Labels: bug, python

#528 Исправить проблему с расчетами формул при обновлении ячеек
  client/components/dcis/grid/GridSheetToolbar.vue
  server/apps/dcis/helpers/cell.py
  server/apps/dcis/services/value_services.py
Labels: enhancement

#532 Добавлен элемент для вычислений
  client/components/dcis/grid/GridCell.vue
Labels: bug

#569 Дивизион заменен на конкретную привязку
  client/components/dcis/periods/AddPeriodDivisions.vue
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/divisions.vue
Labels: invalid

#570 Новое открытое меню свойства строки перекрывает старое
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/controls/GridColumnControl.vue
  client/components/dcis/grid/controls/GridRowControl.vue
Labels: bug, javascript

#577 Добавлена функция подтверждения удаления статуса версии документа
  client/components/dcis/documents/DocumentStatuses.vue
  client/lang/ru/dcis.ts
Labels: enhancement, invalid, javascript

#576 Исправлено переключение листов в таблице периода
  client/pages/dcis/periods/_periodId/sheets.vue
Labels: bug, javascript

#572 Добавлен выбор дивизиона при создании документа
  client/components/dcis/documents/AddDocument.vue
  client/gql/dcis/mutations/document/add_document.graphql
  client/lang/ru/dcis.ts
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/services/document_services.py
Labels: bug, javascript, python, refactoring

#571 Сделана пагинация для загрузки дивизионов
  client/components/dcis/periods/AddPeriodDivisions.vue
  client/components/dcis/periods/AddPeriodUser.vue
  client/gql/dcis/queries/period_possible_divisions.graphql
  client/gql/dcis/queries/project_divisions.graphql
  client/pages/dcis/periods/_periodId/divisions.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/divisions_services.py
Labels: invalid, javascript, python

#582 feat: добавлены хлебные крошки и карточка для документа
  client/components/dcis/Grid.vue
  client/gql/dcis/queries/document.graphql
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId/sheets.vue
  client/types/graphql.d.ts
Labels: enhancement, javascript

#584 Изменено переключение листов для таблиц периода и документа
  client/components/dcis/GridToolbar.vue
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/GridSheets.vue
  client/composables/grid-mutations.ts
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId/sheets.vue
Labels: invalid, javascript

#586 Сделан просмотр файла без редактирования
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellFiles.vue
  client/lang/ru/dcis.ts
Labels: enhancement, invalid, javascript

#587 Сделано отображение статусов документа при отсутствии прав на изменение
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/dcis/documents/DocumentStatusesReadonly.vue
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/documents.vue
Labels: invalid, javascript

#589 Исправлен баг при удалении строки
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/composables/grid.ts
  client/gql/dcis/fragments/cell_fields.graphql
  client/gql/dcis/fragments/row_dimension_fields.graphql
  client/gql/dcis/queries/document_sheet.graphql
  client/gql/dcis/queries/documents_sheet.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/services/sheet_unload_services.py
  server/apps/dcis/tests/permissions/document_permissions.py
Labels: bug, javascript, python

#591 Возвращено случайно удаленное переименование листа
  client/components/dcis/grid/GridSheets.vue
  client/components/dcis/grid/controls/SheetControl.vue
  client/pages/dcis/periods/_periodId/sheets.vue
Labels: bug

#592 Поправлен расчет формул
  server/apps/dcis/helpers/cell.py
Labels: bug

#590 Разделен кеш между таблицей и документом
  client/pages/dcis/documents/_documentId.vue
  client/plugins/apollo.ts
Labels: bug

#593 Обновлена инструкция
  client/components/global/FooterComponent.vue
  client/static/instructions/Инструкция.docx
  client/static/instructions/Сборы_временная инструкция.docx
Labels: documentation

#604 Исправлено неправильное выделение широкой таблицы
  server/apps/dcis/services/sheet_unload_services.py
Labels: bug, python

#605 Исправлен баг при уменьшении строки
  client/components/dcis/grid/GridBody.vue
Labels: bug, javascript

#607 Исправлено неправильное добавление дочерних строк
  client/components/dcis/documents/AddDocument.vue
  server/apps/dcis/services/sheet_services.py
Labels: bug, python
