Repository devind-team/dcis, pull requests merged in 2022-11, with the labels that each got.

#971 Добавлен интерфейс для редактирования организаций в кураторских группах
  .editorconfig
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/curators/ChangeCuratorGroupOrganizations.vue
  client/components/dcis/curators/ChangeCuratorGroupUsers.vue
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/dcis/periods/AddPeriodDivisions.vue
  client/components/dcis/periods/AddPeriodUser.vue
  client/components/dcis/periods/ChangeUserPeriodPrivileges.vue
  client/gql/dcis/mutations/curator/add_organizations_curator_group.graphql
  client/gql/dcis/mutations/curator/delete_organization_curator_group.graphql
  client/gql/dcis/queries/curator_group_new_organizations.graphql
  client/gql/dcis/queries/curator_group_organizations.graphql
  client/lang/ru/curators.ts
  client/pages/panel/ac/curator_groups.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/curator_mutation.py
  server/apps/dcis/schema/queries/curator_queries.py
  server/apps/dcis/services/curator_services.py
  server/apps/dcis/tests/services/curator_services.py
Labels: feature

#985 Настроены разрешения для атрибутов
  client/components/dcis/attributes/AttributesValuesTabItem.vue
  client/components/dcis/attributes/fields/AttributeValueBigmoney.vue
  client/components/dcis/attributes/fields/AttributeValueBool.vue
  client/components/dcis/attributes/fields/AttributeValueDate.vue
  client/components/dcis/attributes/fields/AttributeValueFiles.vue
  client/components/dcis/attributes/fields/AttributeValueMoney.vue
  client/components/dcis/attributes/fields/AttributeValueNumeric.vue
  client/components/dcis/attributes/fields/AttributeValueText.vue
  client/gql/dcis/queries/document.graphql
  client/gql/dcis/queries/period.graphql
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/attributes.vue
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/core/fixtures/006_Privilege.json
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/schema/mutations/attribute_mutations.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/attribute_service.py
  server/apps/dcis/tests/helpers/mock.py
  server/apps/dcis/tests/permissions/document_permissions.py
  server/apps/dcis/tests/permissions/period_permissions.py
Labels: bug, feature, python

#987 Cделан интерфейс изменения ограничений
  client/components/dcis/periods/AddPeriodLimitation.vue
  client/components/dcis/periods/ChangePeriodLimitation.vue
  client/components/dcis/periods/ChangePeriodLimitationsMenu.vue
  client/components/dcis/periods/UpdatePeriodLimitationsFromFile.vue
  client/gql/dcis/fragments/limitation_fields.graphql
  client/gql/dcis/mutations/limitation/add_limitation.graphql
  client/gql/dcis/mutations/limitation/change_limitation.graphql
  client/gql/dcis/mutations/limitation/delete_limitation.graphql
  client/gql/dcis/mutations/limitation/update_limitations_from_file.graphql
  client/gql/dcis/queries/period.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/limitations.vue
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/core/fixtures/006_Privilege.json
  server/apps/dcis/helpers/formula_cache.py
  server/apps/dcis/helpers/limitation_formula_cache.py
  server/apps/dcis/migrations/0032_sheet_limitation.py
  server/apps/dcis/migrations/0034_limitation_index.py
  server/apps/dcis/models/document.py
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/schema/__init__.py
  server/apps/dcis/schema/mutations/__init__.py
  server/apps/dcis/schema/mutations/limitation_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/limitation_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/helpers/__init__.py
  server/apps/dcis/tests/helpers/cell_helpers.py
  server/apps/dcis/tests/helpers/file.py
  server/apps/dcis/tests/helpers/mock.py
  server/apps/dcis/tests/permissions/period_permissions.py
  server/apps/dcis/tests/resources/test_add_update_limitations_from_file.json
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/limitation_services.py
  server/apps/dcis/tests/services/period_services.py
  server/apps/dcis/tests/services/status_services.py
Labels: feature, javascript, python

#989 Доработка ограничений
  server/apps/dcis/tests/services/status_services.py
Labels: python, test

#991 Исправлено отображение организаций у кураторов
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/tests/services/divisions_services.py
Labels: bug, python

#1005 Исправлено удаление проектов и периодов
  client/composables/query-common.ts
  client/composables/query-relay.ts
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/index.vue
Labels: bug, javascript

#1009 Исправлено отображение кавычек в атрибутах
  server/apps/dcis/services/attribute_service.py
  server/apps/dcis/services/cell_service.py
Labels: bug, python

#1021 Изменяем значение в случае успеха операции
  server/apps/dcis/services/excel_extractor_services.py
Labels: bug
