Repository devind-team/dcis, pull requests merged in 2022-03, with the labels that each got.

#31 Вынос ключа шифрования в переменные окружения, осуществление сбора образа при теггировании
  .github/workflows/build.yml
  server/.env.example
  server/devind/settings.py
Labels: bug

#30 Переадресация на проект сборов после авторизации через портал cbias.ru
  client/package.json
  client/pages/auth/cbias/_uid.vue
  client/tailwind.config.js
Labels: wontfix

#32 Установлен идентификатор приложения
  server/devind/settings.py
Labels: enhancement

#35 Добавлены цвета для шрифта, заливки ячеек, границы ячеек и их цвета
  client/components/dcis/Grid.vue
  client/composables/grid.ts
  client/gql/dcis/fragments/cell_fields.graphql
  client/schema.graphql
  client/services/grid.ts
  client/types/graphql.d.ts
  client/types/grid-types.ts
  server/apps/dcis/migrations/0003_auto_20220315_2042.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_extractor.py
  server/apps/dcis/services/excel_unload.py
Labels: enhancement, javascript, python

#41 При вычислении следующей версии добавлено ограничение на период сбора
  server/apps/dcis/schema/mutations/document_mutations.py
Labels: bug

#42 Обновлены серверные зависимости
  server/pyproject.toml
Labels: bug, python

#38 Изменена информация о технчиеской поддержке пользователей
  client/components/global/FooterComponent.vue
  client/package.json
  client/pages/auth/cbias/_uid.vue
  client/schema.graphql
  client/types/graphql.d.ts
Labels: wontfix, javascript

#44 Добавлен элемент индикации загрузки документа
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/documents.vue
  client/pages/dcis/periods/_periodId/index.vue
  client/pages/dcis/projects/_projectId/periods.vue
Labels: wontfix, javascript

#46 Исправлена ошибка загрузки xlsx документа
  client/components/dcis/projects/AddProject.vue
  client/gql/dcis/mutations/project/add_project.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/services/grid.ts
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0003_auto_20220315_2042.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/services/excel_extractor.py
  server/apps/dcis/validators.py
Labels: bug

#47 Проведен некоторый рефакторинг системных файлов на клиенте
  client/components/common/MutationResultAlert.vue
  client/components/common/forms/MutationForm.vue
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/projects/AddProject.vue
  client/components/global/FooterComponent.vue
  client/components/global/ThemeColor.vue
  client/composables/filters.ts
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/validators.py
Labels: wontfix, javascript

#49 Добавлен период в ограничение по установлению следующей версии документа
  server/apps/dcis/migrations/0004_alter_document_unique_together.py
  server/apps/dcis/models/document.py
Labels: bug, python

#51 Исправлено добавление строки при объединенных строках
  client/components/dcis/Grid.vue
  client/gql/dcis/mutations/sheet/add_row_dimension.graphql
  client/gql/dcis/mutations/sheet/delete_row_dimension.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/sheet_mutations.py
Labels: bug, python

#54 Исправлен алгоритм добавления и удаления строк
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/projects/AddPeriod.vue
  client/components/dcis/projects/AddProject.vue
  client/composables/query-relay.ts
  client/gql/dcis/fragments/project_fields.graphql
  client/gql/dcis/mutations/project/change_project.graphql
  client/gql/dcis/mutations/project/delete_project.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/_projectId/settings.vue
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/helpers/__init__.py
  server/apps/dcis/helpers/mutation.py
  server/apps/dcis/migrations/0004_project_archive.py
  server/apps/dcis/migrations/0005_alter_document_unique_together.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_extractor.py
Labels: bug, enhancement, python

#55 Исправлена ошибка при выгрузке документа
  server/apps/dcis/services/excel_extractor.py
  server/apps/dcis/services/excel_unload.py
Labels: bug

#58 Реализация настроек проектов
  client/components/dcis/projects/AddPeriod.vue
  client/components/dcis/projects/AddProject.vue
  client/gql/dcis/fragments/period_fields.graphql
  client/gql/dcis/mutations/project/add_project.graphql
  client/gql/dcis/mutations/project/change_period.graphql
  client/gql/dcis/mutations/project/delete_period.graphql
  client/gql/dcis/queries/project.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/settings.vue
  client/pages/dcis/projects/_projectId/settings.vue
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0006_alter_period_status.py
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/types.py
Labels: enhancement, javascript, python

#59 Исправлена ошибка экспорта файла
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_unload.py
Labels: bug, python

#61 Реализовано удаление периодов
  client/gql/dcis/queries/period.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/documents.vue
  client/pages/dcis/periods/_periodId/settings.vue
  client/pages/dcis/projects/_projectId.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/_projectId/settings.vue
Labels: bug, enhancement, javascript

#63 Исправлена ошибка при добавлении проекта
  server/apps/dcis/schema/mutations/project_mutations.py
Labels: bug

#68 Убрано ошибочное объединение
  server/apps/dcis/models/document.py
Labels: bug, python

#83 Стилистическое оформление документа
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/cells/GridCellDepartment.vue
  client/components/dcis/grid/cells/GridCellMoney.vue
  client/components/dcis/grid/cells/GridCellNumeric.vue
  client/components/dcis/grid/cells/GridCellString.vue
  client/components/dcis/grid/cells/GridCellText.vue
  client/components/dcis/grid/cells/GridCellUser.vue
  client/components/dcis/grid/controls/GridRowControl.vue
  client/composables/grid.ts
  client/gql/dcis/fragments/department_fields.graphql
  client/gql/dcis/queries/departments.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/schema.json
  client/services/grid.ts
  client/types/graphql.d.ts
  client/types/grid-types.ts
  server/apps/dcis/migrations/0007_auto_20220323_0942.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/sheet.py
  server/devind/schema.py
Labels: enhancement, javascript, python

#85 Реализовано множественное выделение ячеек
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellDepartment.vue
  client/components/dcis/grid/cells/GridCellText.vue
  client/composables/grid.ts
  client/services/grid.ts
Labels: enhancement, javascript

#89 Исправлена проблема при удалении строк, которые содержат объединенный ячейки
  server/apps/dcis/models/document.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
Labels: bug

#92 Добавлена панель для редактирования ячеек
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/projects/AddPeriod.vue
  client/components/dcis/projects/AddProject.vue
  client/composables/grid.ts
  client/gql/dcis/mutations/sheet/change_cells_option.graphql
  client/lang/ru/dcis.ts
  client/schema.graphql
  client/services/grid.ts
  client/types/graphql.d.ts
  client/types/grid-types.ts
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/services/cell.py
Labels: enhancement, javascript, python

#95 Убрана проверка на ограничение по индексу из БД
  server/apps/dcis/migrations/0008_auto_20220325_1007.py
  server/apps/dcis/models/sheet.py
Labels: bug, python

#96 Добавлена горизонтальная прокрутка, закреплено рабочее поле
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridHeader.vue
  server/pyproject.toml
Labels: enhancement, javascript

#98 Обновлена версия nodejs. Скрыты warnings при установке зависимостей
  client/Dockerfile
Labels: enhancement

#103 Добавлена дата изменения строки
  client/components/dcis/grid/controls/GridRowControl.vue
  client/gql/dcis/fragments/row_dimension_fields.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0009_rowdimension_updated_at.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/types.py
Labels: enhancement, javascript, python

#112 Исправлена проблема получения идентификатора пользователя
  client/layouts/default.vue
Labels: bug, javascript

#114 На клиенте временно скрыта отрисовка границ
  client/components/dcis/grid/GridBody.vue
Labels: invalid, javascript

#116 Временное добавление файла yarn.lock для сборки проекта
  client/package.json
  client/yarn.lock
Labels: bug, javascript

#117 Убрана функция $snakeToCamel в связи с добавлением scule
  client/components/common/forms/MutationForm.vue
  client/components/common/menu/DateMenu.vue
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/notifications/NotificationsView.vue
  client/components/pages/AddPage.vue
  client/components/pages/ChangePageTags.vue
  client/components/pages/ChangePageTitle.vue
  client/components/pages/sections/add/AddSectionFiles.vue
  client/components/pages/sections/add/AddSectionGallery.vue
  client/components/pages/sections/add/AddSectionText.vue
  client/components/pages/sections/change/ChangeSectionFiles.vue
  client/components/pages/sections/change/ChangeSectionGallery.vue
  client/components/pages/sections/change/ChangeSectionText.vue
  client/components/users/UnloadUsersForm.vue
  client/composables/convertors.ts
  client/composables/filters.ts
  client/composables/index.ts
  client/lang/ru/ac.ts
  client/package.json
  client/pages/auth/cbias/_uid.vue
  client/pages/auth/recovery/index.vue
  client/pages/auth/registration.vue
  client/pages/pages/_pageId/index.vue
  client/plugins/utils.ts
  client/types/vue.d.ts
Labels: bug, dependencies, javascript

#118 Добавлена кнопка меню при просмотре с мобильного телефона
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/attributes.vue
  client/pages/dcis/periods/_periodId/documents.vue
  client/pages/dcis/periods/_periodId/settings.vue
  client/pages/dcis/projects/_projectId.vue
  client/pages/dcis/projects/_projectId/accounts.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/pages/dcis/projects/_projectId/settings.vue
  client/pages/panel/ac.vue
Labels: bug, javascript
