Repository devind-team/dcis, pull requests merged in 2022-06, with the labels that each got.

#356 Исправлено поведение вывода привилегий в компоненте
  client/components/dcis/periods/PeriodGroupPrivileges.vue
  client/components/dcis/periods/PeriodGroupUsers.vue
  client/pages/dcis/periods/_periodId/users.vue
Labels: bug

#359 Добавлена библиотека расчета формул и библиотека кеширования результатов
  server/.env.example
  server/apps/dcis/models/sheet.py
  server/apps/dcis/services/excel_extractor_services.py
  server/devind/settings.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, python

#372 Реализовано переименование листов
  client/components/dcis/Grid.vue
  client/components/dcis/common/RenameDialog.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/controls/SheetControl.vue
  client/composables/grid-resizing.ts
  client/composables/grid.ts
  client/gql/dcis/mutations/sheet/rename_sheet.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId.vue
  client/pages/profile/security.vue
  client/schema.graphql
  client/services/grapqhl/mutations/dcis/sheet_mutations.ts
  client/types/graphql.d.ts
  docker-compose.yml
  server/.env.example
  server/apps/dcis/migrations/0019_alter_periodgroup_options.py
  server/apps/dcis/permissions.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/sheet_services.py
  server/devind/settings.py
  server/poetry.lock
Labels: enhancement, feature, javascript, python

#388 387 описание процессов работы
  readme.md
Labels: documentation

#390 При добавлении проекта, добавляется пользователь
  server/apps/dcis/schema/mutations/project_mutations.py
Labels: bug

#392 Формирование дерева расчета по экселевским формулам
  client/components/dcis/projects/AddPeriod.vue
  client/gql/dcis/mutations/project/add_period.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId.vue
  client/schema.graphql
  client/types/graphql.d.ts
  client/yarn.lock
  server/Dockerfile
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/sheet_cache_service.py
  server/apps/dcis/tests.py
  server/apps/dcis/tests/__init__.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, feature, javascript, python

#378 Добавлено редактирование объектов(дивизионов) периода
  client/components/dcis/periods/ChangeDivisions.vue
  client/components/dcis/periods/CopyPeriodGroups.vue
  client/components/dcis/periods/Divisions.vue
  client/gql/dcis/mutations/project/change_divisions.graphql
  client/gql/dcis/mutations/project/delete_division.graphql
  client/gql/dcis/queries/divisions.graphql
  client/gql/dcis/queries/period.graphql
  client/gql/pages/fragments/section_fields.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId/divisions.vue
  client/pages/dcis/periods/_periodId/users.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  client/yarn.lock
  server/apps/core/management/seed/003.devind_dictionaries/005.Department.json
  server/apps/dcis/migrations/0020_alter_division_unique_together.py
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/__init__.py
  server/apps/dcis/schema/mutations/privilege_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/types.py
Labels: feature, javascript, python

#395 Ограниченный вывод проектов
  client/components/dcis/ui/WaveContainer.vue
  client/gql/core/queries/me.graphql
  client/gql/dcis/queries/divisions.graphql
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/schema.json
  client/services/grapqhl/queries/dcis/divisions.ts
  client/services/grapqhl/queries/dcis/projects.ts
  client/types/graphql.d.ts
  server/apps/core/models.py
  server/apps/core/schema/types.py
  server/apps/dcis/schema/queries/privilege_queries.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/project_services.py
Labels: enhancement, feature, javascript, python

#420 Ограниченный вывод периодов сборов
  client/gql/dcis/mutations/project/add_period.graphql
  client/gql/dcis/queries/periods.graphql
  client/gql/dcis/queries/project.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/schema.graphql
  client/services/grapqhl/queries/dcis/periods.ts
  client/types/graphql.d.ts
  client/yarn.lock
  docs/document_rules.md
  readme.md
  server/apps/core/management/seed/005.dcis/001.Privilege.json
  server/apps/core/models.py
  server/apps/core/schema/types.py
  server/apps/dcis/helpers/divisions.py
  server/apps/dcis/management/commands/seed_dcis.py
  server/apps/dcis/permissions.py
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/permissions/project_permissions.py
  server/apps/dcis/permissions/sheet_permissions.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/services/privilege_services.py
  server/apps/dcis/services/project_services.py
  server/poetry.lock
Labels: enhancement, javascript, python
