Repository devind-team/dcis, pull requests merged in 2022-04, with the labels that each got.

#127 Исправлена проблема с пагинацией
  client/composables/query-relay.ts
Labels: bug, javascript

#129 Изменение папки client/.nuxt -> client/nuxt-dist
  client/.dockerignore
  client/components/dcis/grid/cells/GridCellMoney.vue
  client/components/profile/ProfileInformation.vue
  client/components/users/AddUsersMenu.vue
  client/components/users/AvatarView.vue
  client/components/users/ChangeUsers.vue
  client/components/users/ChangeUsersList.vue
  client/layouts/default.vue
  client/middleware/check-auth.ts
  client/nuxt.config.ts
  client/pages/dcis/periods/_periodId/settings.vue
  client/pages/pages/_pageId/section/_sectionId.vue
  client/pages/pages/_pageId/section/add.vue
  client/pages/panel/ac/users.vue
  client/tsconfig.json
  server/.gitignore
  server/poetry.lock
Labels: enhancement, javascript

#156 Некоторое изменение типа фильтров проектов
  server/apps/dcis/filters.py
  server/apps/dcis/schema/types.py
Labels: wontfix, python

#158 Исправлена схема БД, связанная с дивизионами
  client/components/dcis/documents/SettingsDocument.vue
  client/components/dcis/documents/UploadDocument.vue
  client/components/dcis/periods/Divisions.vue
  client/components/dcis/projects/AddProject.vue
  client/gql/dcis/fragments/department_fields.graphql
  client/gql/dcis/fragments/organization_fields.graphql
  client/gql/dcis/fragments/project_fields.graphql
  client/gql/dcis/fragments/row_dimension_fields.graphql
  client/gql/dcis/mutations/document/unload_document.graphql
  client/gql/dcis/mutations/project/add_project.graphql
  client/gql/dcis/queries/organizations.graphql
  client/lang/ru/dcis.ts
  client/nuxt.config.ts
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/divisions.vue
  client/pages/dcis/projects/_projectId.vue
  client/pages/dcis/projects/_projectId/accounts.vue
  client/pages/index.vue
  client/schema.graphql
  client/schema.json
  client/tsconfig.json
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0011_auto_20220406_1716.py
  server/apps/dcis/models/__init__.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/privilege.py
  server/apps/dcis/models/project.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_unload.py
  server/poetry.lock
Labels: wontfix, python

#163 Реализовано изменение ширины колонок в редакторе
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridColumnWidth.vue
  client/components/dcis/grid/GridHeader.vue
  client/composables/grid.ts
  client/gql/dcis/fragments/column_dimension_fields.graphql
  client/gql/dcis/mutations/sheet/change_column_dimension.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  client/types/grid-types.ts
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/types.py
Labels: enhancement, javascript

#166 Добавлена служебная информация при выгрузке документов
  client/components/dcis/documents/DocumentUnload.vue
  client/components/dcis/documents/SettingsDocument.vue
  client/composables/color-mode.ts
  client/lang/ru/dcis.ts
  client/layouts/default.vue
  client/package.json
  client/yarn.lock
  server/apps/core/models.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/services/document_unload.py
  server/apps/dcis/services/excel_unload.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, dependencies, javascript, python

#168 Исправлена проблема с установлением зависимостей при сборке клиентского контейнера
  client/Dockerfile
Labels: bug, javascript

#170 Убран файл зависимостей из игнора при сборке docker образа.
  client/.dockerignore
Labels: bug, javascript

#171 Изменен механизм построения docker образа
  client/Dockerfile
Labels: bug, javascript

#173 Изменен механизм сборки серверного docker контейнера
  server/Dockerfile
  server/whitelist.txt
Labels: enhancement, python

#184 Исправлены стили для фиксированного первого столбца, добавлено выделение для строк и столбцов
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/controls/GridRowControl.vue
  client/composables/grid.ts
  client/nuxt.config.ts
  client/package.json
  client/plugins/detect-browser.ts
  client/services/grid.ts
  client/tsconfig.json
  client/types/grid-types.ts
Labels: bug, enhancement

#190 Убрана зависимость от RxJS
  client/components/common/DropFileUpload.vue
  client/components/common/FileField.vue
  client/components/common/ImageGallery.vue
  client/components/common/MutationResultAlert.vue
  client/components/common/filters/QueryDataFilter.vue
  client/components/common/forms/MutationForm.vue
  client/components/dashboard/general/RequestStatistics.vue
  client/components/pages/AddPage.vue
  client/components/pages/ChangePageKind.vue
  client/components/pages/PageSections.vue
  client/components/pages/PageSegment.vue
  client/components/pages/PageView.vue
  client/components/pages/SectionActions.vue
  client/components/pages/sections/change/ChangeSectionText.vue
  client/components/pages/sections/views/SectionUsers.vue
  client/components/users/AvatarView.vue
  client/composables/filters.ts
  client/composables/index.ts
  client/composables/vuetify.ts
  client/gql/pages/queries/pages.graphql
  client/layouts/default.vue
  client/layouts/error.vue
  client/middleware/auth.ts
  client/middleware/check-auth.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/auth/login.vue
  client/pages/auth/logout.vue
  client/pages/auth/recovery/_token.vue
  client/pages/auth/recovery/index.vue
  client/pages/auth/registration.vue
  client/pages/auth/verification.vue
  client/pages/categories/_categoryId.vue
  client/pages/categories/_categoryId/add_page.vue
  client/pages/categories/_categoryId/index.vue
  client/pages/notifications/_notificationId.vue
  client/pages/pages/_pageId/section/_sectionId.vue
  client/pages/pages/_pageId/section/add.vue
  client/pages/panel/support/index.vue
  client/pages/profile/index.vue
  client/pages/profile/security.vue
  client/pages/users/_user_id.vue
  client/plugins/apollo-init.ts
  client/plugins/apollo.ts
  client/plugins/rx.ts
  client/types/vue.d.ts
  client/yarn.lock
  server/apps/pages/schema/mutations/page_mutations.py
  server/devind/ws_consumer.py
  server/poetry.lock
Labels: dependencies, javascript

#191 Сделано массовое выделение строк и столбцов
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/controls/GridRowControl.vue
  client/composables/grid.ts
  client/static/cursors/arrow-down.svg
  client/static/cursors/arrow-right.svg
Labels: enhancement, javascript

#199 Добавлена инструкция
  client/components/global/FooterComponent.vue
  client/static/instructions/Сборы_временная инструкция.docx
Labels: documentation

#198 Исправлена проблема с миграциями в модели проекта
  client/yarn.lock
  server/apps/dcis/migrations/0012_alter_project_content_type.py
  server/apps/dcis/models/project.py
  server/poetry.lock
Labels: bug

#200 Изменено отображение статуса периода
  client/lang/ru/dcis.ts
  client/pages/dcis/projects/_projectId/periods.vue
  server/apps/dcis/migrations/0012_alter_project_content_type.py
Labels: wontfix, javascript

#203 Добавлено изменение комментария у версий сбора
  client/gql/dcis/mutations/document/change_document_comment.graphql
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
Labels: feature, javascript, python

#220 Формирование нового документа со значениями из выбираемой версии
  client/components/dcis/Grid.vue
  client/components/dcis/documents/AddDocument.vue
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/composables/grid.ts
  client/composables/query-relay.ts
  client/gql/dcis/fragments/cell_fields.graphql
  client/gql/dcis/fragments/division_model_fields.graphql
  client/gql/dcis/fragments/document_fields.graphql
  client/gql/dcis/mutations/document/add_document.graphql
  client/gql/dcis/mutations/document/delete_document_status.graphql
  client/gql/dcis/queries/documents.graphql
  client/gql/dcis/queries/period.graphql
  client/gql/dcis/queries/user_divisions.graphql
  client/lang/ru/dcis.ts
  client/package.json
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  server/apps/core/models.py
  server/apps/dcis/models/project.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/queries/sheet_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/document_unload.py
  server/apps/pages/schema/__init__.py
  server/poetry.lock
  server/pyproject.toml
Labels: bug, enhancement, dependencies, javascript, python

#224 Добавлено поле типа файл
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellFiles.vue
  client/components/dcis/grid/cells/GridCellText.vue
  client/composables/grid.ts
  client/composables/query-common.ts
  client/gql/dcis/mutations/document/change_file_value.graphql
  client/gql/dcis/mutations/document/change_value.graphql
  client/gql/dcis/mutations/document/unload_file_value_archive.graphql
  client/gql/dcis/mutations/sheet/change_cells_option.graphql
  client/gql/dcis/queries/value_files.graphql
  client/lang/en/main.ts
  client/lang/ru/dcis.ts
  client/lang/ru/main.ts
  client/schema.graphql
  client/types/graphql.d.ts
  client/types/grid-types.ts
  server/apps/dcis/migrations/0013_add_value_payload.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/schema/queries/sheet_queries.py
  server/apps/dcis/services/cell.py
  server/apps/dcis/services/value.py
  server/devind/settings.py
Labels: enhancement

#227 Исправлен баг при удалении строки
  client/components/dcis/grid/controls/GridRowControl.vue
  client/gql/dcis/queries/document.graphql
Labels: bug

#228 Добавлен тип поля КБК
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/cells/GridCellClassification.vue
  client/components/dcis/grid/cells/GridCellDepartment.vue
  client/components/dcis/grid/cells/GridCellFiles.vue
  client/components/dcis/grid/cells/GridCellMoney.vue
  client/components/dcis/grid/cells/GridCellNumeric.vue
  client/components/dcis/grid/cells/GridCellString.vue
  client/components/dcis/grid/cells/GridCellText.vue
  client/components/dcis/grid/cells/GridCellUser.vue
  client/components/global/FooterComponent.vue
  client/composables/grid.ts
  client/gql/dcis/queries/active_budget_classifications.graphql
  client/gql/dcis/queries/budget_classifications.graphql
  client/lang/ru/dcis.ts
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0014_auto_20220425_1137.py
  server/apps/dcis/models/sheet.py
  server/poetry.lock
Labels: feature, dependencies, javascript, python

#233 Наследование ячейками типов колонок при добавлении новых строк
  client/yarn.lock
  server/apps/dcis/schema/mutations/sheet_mutations.py
Labels: enhancement, python

#237 Документирование и очистка
  .gitlab-ci.yml
  .graphqlconfig
  client/package.json
  docs/code_style/server/models.md
  docs/code_style/server/permissions.md
  init.py
  init.sh
  readme.md
  server/pyproject.toml
Labels: documentation

#238 Исправлен баг при смене типа ячейки файл
  .gitignore
  client/.dockerignore
  client/components/dcis/Grid.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/cells/GridCellFiles.vue
  client/gql/dcis/mutations/sheet/change_cells_option.graphql
  client/gql/dcis/mutations/sheet/change_file_value.graphql
  client/gql/dcis/mutations/sheet/change_value.graphql
  client/gql/dcis/mutations/sheet/unload_file_value_archive.graphql
  client/nuxt.config.ts
  client/tsconfig.json
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/project_mutations.py
  server/apps/dcis/schema/mutations/sheet_mutations.py
  server/apps/dcis/services/cell.py
Labels: bug
