Repository devind-team/dcis, pull requests merged in 2023-04, with the labels that each got.

#1364 Улучшен вывод периодов
  client/components/dcis/attributes/AddAttributeMenu.vue
  client/components/dcis/periods/DocumentStatusFilter.vue
  client/components/dcis/periods/PeriodStatusFilter.vue
  client/gql/dcis/queries/periods.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/documents.vue
  client/pages/dcis/periods/_periodId/unload.vue
  client/pages/dcis/projects/_projectId/periods.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/add_document_data_services.py
  server/apps/dcis/services/period_services.py
  server/poetry.lock
Labels: feature, javascript, python

#1366 Обновлена библиотека devind-dictionaries
  server/poetry.lock
  server/pyproject.toml
Labels: dependencies

#1378 В фильтр организаций добавлен фильтр типа организации
  client/components/common/filters/ItemsDataFilter.vue
  client/components/dcis/periods/OrganizationFilter.vue
  client/components/dcis/periods/OrganizationLevelFilter.vue
  client/gql/dcis/queries/organizations.graphql
  client/gql/dcis/queries/period_filter_organizations.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/services/period_services.py
  server/poetry.lock
  server/pyproject.toml
Labels: feature, javascript, python

#1387 Исправлена ошибка при добавлении группы в период
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/services/period_services.py
Labels: bug, python

#1389 Скрыт столбец Версия в разделе Мониторинг
  client/components/dcis/documents/DocumentsTable.vue
  client/pages/dcis/periods/_periodId/settings.vue
Labels: feature, javascript

#1385 Исправлена ошибка добавление атрибута через форму
  client/components/dcis/attributes/AddAttribute.vue
  client/components/dcis/attributes/ChangeAttribute.vue
  client/gql/dcis/mutations/attributes/add_attribute.graphql
  client/gql/dcis/mutations/attributes/change_attribute.graphql
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/forms.py
  server/apps/dcis/schema/mutations/attribute_mutations.py
  server/apps/dcis/services/attribute_services.py
  server/apps/dcis/tests/services/attribute_service.py
  server/apps/dcis/tests/services/period_services.py
Labels: bug, javascript

#1403 Исправлена выгрузка документов для организаций
  client/components/dcis/documents/DocumentUnload.vue
  client/components/dcis/grid/menus/DocumentUnloadMenu.vue
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId.vue
  client/pages/dcis/documents/_documentId/sheets.vue
  client/pages/dcis/projects/_projectId/periods.vue
  server/apps/dcis/migrations/0045_alter_cell_vertical_align.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/attribute_mutations.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/services/attribute_services.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/document_unload_services.py
  server/apps/dcis/services/period_unload_services.py
  server/apps/dcis/services/status_services.py
  server/apps/dcis/services/value_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/resources/document_unload_services/test_department_with_all_additional.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_department_with_row_add_date_additional.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_department_with_wrong_additional.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_department_without_additional.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_organization_branch.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_organization_with_children_rows.xlsx
  server/apps/dcis/tests/resources/document_unload_services/test_organization_without_children_rows.xlsx
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/attribute_service.py
  server/apps/dcis/tests/services/column_dimension_services.py
  server/apps/dcis/tests/services/common.py
  server/apps/dcis/tests/services/curator_services.py
  server/apps/dcis/tests/services/document_services.py
  server/apps/dcis/tests/services/document_unload_services.py
  server/apps/dcis/tests/services/limitation_services.py
  server/apps/dcis/tests/services/period_unload_services.py
  server/apps/dcis/tests/services/project_services.py
  server/apps/dcis/tests/services/row_dimension_services.py
  server/apps/dcis/tests/services/status_services.py
  server/devind/settings.py
  server/templates/mail/auth/changed_password.html
  server/templates/mail/auth/confirm_email.html
  server/templates/mail/auth/recovery_password.html
  server/templates/mail/auth/register.html
  server/templates/mail/auth/request_code.html
  server/templates/mail/conference/notification.html
  server/templates/mail/conference/readme.md
  server/templates/mail/index.html
Labels: invalid, javascript, python

#1400 Добавлен раздел для порсмотра методического обеспечения
  client/gql/dcis/fragments/period_methodical_support_fields.graphql
  client/gql/dcis/mutations/period/add_period_methodical_support.graphql
  client/gql/dcis/mutations/period/change_period_methodical_support.graphql
  client/gql/dcis/mutations/period/delete_period_methodical_support.graphql
  client/gql/dcis/queries/period_methodical_support.graphql
  client/lang/ru/dcis.ts
  client/lang/ru/profile.ts
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/support.vue
  client/pages/profile/files.vue
  client/schema.graphql
  client/schema.json
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/core/fixtures/006_Privilege.json
  server/apps/dcis/migrations/0046_add_period_methodical_support.py
  server/apps/dcis/models/__init__.py
  server/apps/dcis/models/methodical_support.py
  server/apps/dcis/models/project.py
  server/apps/dcis/permissions/period_permissions.py
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/models/__init__.py
  server/apps/dcis/tests/models/methodical_support.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/period_methodical_support_services.py
  server/apps/dcis/tests/tests_helpers/file.py
  server/poetry.lock
Labels: enhancement, feature, javascript, python

#1409 Удален профиль пользователя
  client/components/global/AvatarMenu.vue
  client/components/notifications/NotificationsMenu.vue
  client/pages/notifications/index.vue
  client/pages/panel/ac/activity.vue
  client/pages/profile.vue
  client/pages/profile/activity.vue
  client/pages/profile/files.vue
  client/pages/profile/history.vue
  client/pages/profile/index.vue
  client/pages/profile/me.vue
  client/pages/profile/security.vue
  client/pages/profile/settings.vue
Labels: javascript, refactoring

#1429 Сделан перевод формул
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/formula_services.py
  server/apps/dcis/services/limitation_services.py
  server/apps/dcis/services/status_services.py
  server/apps/dcis/tests/permissions/document_permissions.py
  server/apps/dcis/tests/resources/limitation_services/test_add_limitations_from_file_not_dict.json
  server/apps/dcis/tests/resources/limitation_services/test_add_limitations_from_file_not_list.json
  server/apps/dcis/tests/resources/limitation_services/test_add_limitations_from_file_wrong_json.json
  server/apps/dcis/tests/resources/limitation_services/test_add_limitations_from_file_wrong_keys.json
  server/apps/dcis/tests/resources/limitation_services/test_add_limitations_from_file_wrong_sheet.json
  server/apps/dcis/tests/resources/limitation_services/test_add_update_limitations_from_file.json
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/document_services.py
  server/apps/dcis/tests/services/formula_services.py
  server/apps/dcis/tests/services/limitation_services.py
  server/apps/dcis/tests/services/period_methodical_support_services.py
  server/apps/dcis/tests/tests_helpers/file.py
Labels: feature, javascript, python

#1431 Улучшена работа с формулами
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/menus/EditMenu.vue
  client/components/dcis/grid/menus/RecalculationMenu.vue
  client/components/dcis/grid/menus/ViewMenu.vue
  client/components/dcis/grid/properties/AggregationProperty.vue
  client/components/dcis/grid/properties/FormulaProperty.vue
  client/composables/grid-local-mutations.ts
  client/composables/grid-permissions.ts
  client/composables/grid.ts
  client/gql/dcis/mutations/cell/change_cell_formula.graphql
  client/gql/dcis/mutations/values/recalculate_all_cells.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/sheets.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/helpers/cell.py
  server/apps/dcis/migrations/0047_delete_formula_kind.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/mutations/cell_mutations.py
  server/apps/dcis/schema/mutations/value_mutations.py
  server/apps/dcis/services/aggregation_services.py
  server/apps/dcis/services/excel_extractor_services.py
  server/apps/dcis/services/period_unload_services.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/services/sheet_unload_services.py
  server/apps/dcis/services/value_services.py
  server/apps/dcis/tasks.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/sheet_services.py
  server/apps/dcis/tests/services/values_services.py
Labels: feature, javascript, python
