Repository devind-team/dcis, pull requests merged in 2023-03, with the labels that each got.

#1266 Сделана работа с буфером обмена
  client/components/common/filters/BaseDataFilter.vue
  client/components/dcis/documents/DocumentUnload.vue
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridCell.vue
  client/components/dcis/grid/GridSheetMenu.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/GridSheets.vue
  client/components/dcis/grid/clipboard/ClipboardTable.vue
  client/components/dcis/grid/menus/DocumentUnloadMenu.vue
  client/components/dcis/grid/menus/EditMenu.vue
  client/components/dcis/grid/menus/ReportUnloadMenu.vue
  client/components/dcis/grid/menus/TableSettingsMenu.vue
  client/components/dcis/periods/ChangeShowSheets.vue
  client/components/dcis/periods/ReportDocumentFilter.vue
  client/components/dcis/periods/ReportSettingsMenu.vue
  client/composables/grid-actions.ts
  client/composables/grid-choice.ts
  client/composables/grid-clipboard.ts
  client/composables/grid-mutations.ts
  client/composables/grid-permissions.ts
  client/composables/grid-selection.ts
  client/composables/grid.ts
  client/gql/dcis/mutations/cell/change_cell_default.graphql
  client/gql/dcis/mutations/cell/paste_into_cells.graphql
  client/gql/dcis/mutations/values/change_values.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId/sheets.vue
  client/pages/dcis/periods/_periodId/report.vue
  client/pages/dcis/periods/_periodId/sheets.vue
  client/schema.graphql
  client/services/grid.ts
  client/types/graphql.d.ts
  server/apps/dcis/helpers/cell.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/ordering.py
  server/apps/dcis/schema/mutations/aggregation_mutation.py
  server/apps/dcis/schema/mutations/attribute_mutations.py
  server/apps/dcis/schema/mutations/cell_mutations.py
  server/apps/dcis/schema/mutations/value_mutations.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/add_document_data_services.py
  server/apps/dcis/services/aggregation_services.py
  server/apps/dcis/services/attribute_services.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/services/value_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/aggregation_services.py
  server/apps/dcis/tests/services/sheet_services.py
  server/apps/dcis/tests/services/values_services.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, javascript, python

#1291 Исправление бага при добавлении агрегации
  client/components/dcis/periods/AddPeriodAggregationCell.vue
  client/pages/dcis/periods/_periodId/aggregations.vue
Labels: bug

#1290 Исправлено неправильное поведение копирования
  client/components/dcis/grid/clipboard/ClipboardTable.vue
Labels: bug, javascript

#1289 Исправлен баг при выборе ячеек для агрегации
  client/components/dcis/grid/GridChoiceCells.vue
  client/components/dcis/grid/properties/AggregationProperty.vue
  client/composables/grid-choice.ts
  client/lang/en/main.ts
  client/lang/ru/main.ts
Labels: bug, javascript

#1288 Ускорена проверка ограничений
  client/components/dcis/documents/DocumentStatuses.vue
  server/apps/dcis/services/status_services.py
Labels: invalid, javascript, python

#1281 Добавить экспорт и импорт атрибутов из файла
  client/components/dcis/attributes/AddAttribute.vue
  client/components/dcis/attributes/AddAttributeMenu.vue
  client/components/dcis/attributes/UploadAttributesFromFile.vue
  client/gql/dcis/fragments/attribute_fields.graphql
  client/gql/dcis/mutations/attributes/unload_attributes_in_file.graphql
  client/gql/dcis/mutations/attributes/upload_attributes_from_file.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/attributes.vue
  client/schema.graphql
  client/static/templates/Атребуты.json
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/attribute_mutations.py
  server/apps/dcis/services/attribute_services.py
  server/apps/dcis/tests/services/attribute_service.py
Labels: enhancement, feature, javascript, python, test

#1297 Скрыть лишние организации в фильтре организаций
  client/components/dcis/periods/OrganizationFilter.vue
  client/gql/dcis/queries/organizations_has_not_document.graphql
  client/gql/dcis/queries/organizations_without_document.graphql
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/divisions_services.py
  server/apps/dcis/tests/services/period_services.py
Labels: invalid, javascript, python

#1298 Сделана выгрузка только доступных организаций
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/unload.vue
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/period_unload_services.py
  server/apps/dcis/tests/resources/period_unload_services/test_without_filter_admin.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_without_filter_curator.xlsx
  server/apps/dcis/tests/services/period_unload_services.py
Labels: invalid, javascript, python

#1300 Сделать экспорт агрегации в файл
  client/components/dcis/periods/ChangePeriodAggregationCellsMenu.vue
  client/gql/dcis/mutations/aggregation/unload_aggregations_in_file.graphql
  client/gql/dcis/queries/aggregation_cells.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/aggregations.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/aggregation_mutation.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/services/aggregation_services.py
  server/apps/dcis/tests/services/aggregation_services.py
Labels: feature, javascript, python

#1301 Сделать экспорт ограничений в файл
  client/components/dcis/periods/ChangePeriodLimitationsMenu.vue
  client/gql/dcis/mutations/limitation/unload_limitations_in_file.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/limitations.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/limitation_mutations.py
  server/apps/dcis/services/limitation_services.py
  server/apps/dcis/tests/services/limitation_services.py
Labels: feature, javascript, python

#1305 Для выгрузки формата Зверева добавлен фильтр "Тип организации"
  client/components/dcis/periods/OrganizationFilter.vue
  client/components/dcis/periods/OrganizationKindFilter.vue
  client/gql/dcis/mutations/period/unload_period.graphql
  client/gql/dcis/queries/period_filter_departments.graphql
  client/gql/dcis/queries/period_filter_organizations.graphql
  client/gql/dcis/queries/period_organization_kinds.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/unload.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/services/divisions_services.py
  server/apps/dcis/services/period_unload_services.py
  server/apps/dcis/tests/resources/period_unload_services/test_organization_kind_filter.xlsx
  server/apps/dcis/tests/services/period_unload_services.py
Labels: feature, javascript, python

#1310 Исправлен баг наложения при наличии закрепленных строк
  client/pages/dcis/documents/_documentId/sheets.vue
Labels: bug, javascript

#1320 Запрещено редактирование агрегирующей ячейки
  client/composables/grid-permissions.ts
  server/apps/dcis/migrations/0001_initial.py
  server/apps/dcis/migrations/0043_delete_extra_value.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/services/value_services.py
  server/apps/dcis/tests/services/values_services.py
Labels: invalid, javascript, python

#1322 Исправлены ошибки при переключении листов
  client/composables/grid-resizing.ts
  client/composables/grid-selection.ts
  client/pages/dcis/periods/_periodId/report.vue
  client/types/grid.ts
Labels: bug, javascript

#1327 Улучшить форматирование json файлов
  server/apps/dcis/services/aggregation_services.py
  server/apps/dcis/services/attribute_services.py
  server/apps/dcis/services/limitation_services.py
Labels: invalid, python

#1337 Добавить поиск проектов
  client/components/dcis/projects/ProjectsFilter.vue
  client/composables/pagination.ts
  client/gql/dcis/queries/projects.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/projects/index.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/filters.py
  server/apps/dcis/schema/queries/project_queries.py
  server/apps/dcis/schema/types.py
Labels: feature, javascript, python

#1339 Создана архивная версия документа
  client/components/common/grid/LeftNavigatorDriver.vue
  client/components/dcis/attributes/fields/AttributeValueBigmoney.vue
  client/components/dcis/attributes/fields/AttributeValueBool.vue
  client/components/dcis/attributes/fields/AttributeValueDate.vue
  client/components/dcis/attributes/fields/AttributeValueFiles.vue
  client/components/dcis/attributes/fields/AttributeValueMoney.vue
  client/components/dcis/attributes/fields/AttributeValueNumeric.vue
  client/components/dcis/attributes/fields/AttributeValueText.vue
  client/components/dcis/documents/DocumentStatuses.vue
  client/components/dcis/documents/DocumentsTable.vue
  client/gql/dcis/fragments/add_status_fields.graphql
  client/gql/dcis/mutations/document/add_document_status.graphql
  client/gql/dcis/queries/document_statuses.graphql
  client/lang/ru/dcis.ts
  client/lang/ru/dictionaries.ts
  client/pages/dcis/periods/archive/_archiveId.vue
  client/pages/dcis/periods/archive/_archiveId/attributes.vue
  client/pages/dcis/periods/archive/_archiveId/document_sheets.vue
  client/pages/dcis/periods/archive/_archiveId/index.vue
  client/pages/dcis/periods/archive/_archiveId/period_sheets.vue
  client/pages/dcis/periods/archive/index.vue
  client/pages/panel/dictionaries/add_statuses.vue
  client/schema.graphql
  client/types/devind.d.ts
  client/types/graphql.d.ts
  server/apps/core/fixtures/008_AddStatus.json
  server/apps/dcis/migrations/0044_add_archive.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/project.py
  server/apps/dcis/models/sheet.py
  server/apps/dcis/schema/queries/period_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/period_services.py
  server/apps/dcis/services/status_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/status_services.py
  server/poetry.lock
  server/pyproject.toml
Labels: enhancement, feature, javascript, python
