Repository devind-team/dcis, pull requests merged in 2023-02, with the labels that each got.

#1179 Исправлен баг при выборе ячеек только для чтения
  client/components/dcis/grid/GridSheetToolbar.vue
Labels: bug, javascript

#1178 Исправлен баг при перезагрузке страницы с таблицей
  client/composables/grid-local-mutations.ts
  client/nuxt.config.ts
Labels: bug, javascript

#1200 Продублированы комментарии статусов в блоке комментариев к документу
  client/components/dcis/documents/DocumentStatuses.vue
  client/gql/dcis/fragments/document_message_fields.graphql
  client/gql/dcis/mutations/document/add_document_message.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/documents/_documentId/comments.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/migrations/0041_remove_document_comment.py
  server/apps/dcis/migrations/0042_move_document_status.py
  server/apps/dcis/models/messages.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/add_document_data_services.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/services/status_services.py
  server/apps/dcis/tests/services/document_services.py
Labels: invalid, javascript

#1202 Переименован раздел "Комментарии" в "Журнал"
  client/lang/ru/dcis.ts
Labels: enhancement

#1231 Сделан сервис для загрузки агрегации в ячейках
  .editorconfig
  client/components/dcis/periods/AddPeriodAggregationCell.vue
  client/components/dcis/periods/ChangePeriodAggregationCellsMenu.vue
  client/components/dcis/periods/UpdatePeriodAggregationCellsFromFile.vue
  client/gql/dcis/mutations/aggregation/add_aggregation.graphql
  client/gql/dcis/mutations/aggregation/delete_aggregation.graphql
  client/gql/dcis/mutations/aggregation/update_aggregations_from_file.graphql
  client/gql/dcis/queries/aggregation_cells.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId.vue
  client/pages/dcis/periods/_periodId/aggregations.vue
  client/schema.graphql
  client/static/templates/Агрегация.json
  client/types/graphql.d.ts
  server/apps/dcis/helpers/pydantic_translate.py
  server/apps/dcis/schema/__init__.py
  server/apps/dcis/schema/mutations/__init__.py
  server/apps/dcis/schema/mutations/aggregation_mutation.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/cell_service.py
  server/apps/dcis/services/sheet_services.py
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/cell_services.py
  server/poetry.lock
  server/pyproject.toml
Labels: feature, javascript, python, test
