Repository devind-team/dcis, pull requests merged in 2023-01, with the labels that each got.

#1116 Сделан предварительный вариант выгрузки формата Зверева
  client/gql/dcis/mutations/period/unload_period.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/unload.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_unload_services.py
Labels: feature, javascript, python

#1129 Добавлена сортировка столбцов в документах
  client/components/dcis/documents/DocumentsTable.vue
  client/gql/dcis/queries/documents.graphql
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/services/ordering.ts
  client/types/graphql.d.ts
  server/apps/dcis/filters.py
  server/apps/dcis/helpers/ordering.py
  server/apps/dcis/migrations/0039_add_document_updated_by.py
  server/apps/dcis/migrations/0040_denormalize_document_last_status.py
  server/apps/dcis/models/document.py
  server/apps/dcis/ordering.py
  server/apps/dcis/schema/queries/document_queries.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/helpers/__init__.py
  server/apps/dcis/tests/helpers/ordering.py
  server/apps/dcis/tests/models/__init__.py
  server/apps/dcis/tests/models/document.py
  server/apps/dcis/tests/ordering.py
Labels: invalid, javascript, python

#1151 Доделана реализация выгрузки формата Зверева
  client/components/common/forms/MutationForm.vue
  client/gql/dcis/mutations/period/unload_period.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/unload.vue
  client/schema.graphql
  client/types/graphql.d.ts
  server/apps/dcis/schema/mutations/period_mutations.py
  server/apps/dcis/services/period_unload_services.py
  server/apps/dcis/tests/__init__.py
  server/apps/dcis/tests/resources/period_unload_services/test_apply_number_format.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_empty_cell.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_organization_filter.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_status_filter.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_unload_children.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_unload_default.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_unload_heads_and_children.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_unload_without_document.xlsx
  server/apps/dcis/tests/resources/period_unload_services/test_without_filter.xlsx
  server/apps/dcis/tests/services/__init__.py
  server/apps/dcis/tests/services/period_unload_services.py
Labels: feature, javascript, python

#1165 Убрана бесконечная загрузка на главной странице
  client/pages/index.vue
Labels: invalid, javascript

#1167 Исправлен баг при отображении проектов
  client/pages/dcis/projects/index.vue
  client/services/grapqhl/queries/dcis/projects.ts
Labels: bug, javascript

#1166 1155 удалить комментарий документа
  client/components/dcis/documents/AddDocument.vue
  client/components/dcis/documents/AddDocumentData.vue
  client/components/dcis/documents/DocumentsTable.vue
  client/gql/dcis/fragments/document_fields.graphql
  client/gql/dcis/mutations/document/add_document.graphql
  client/gql/dcis/mutations/document/add_document_data.graphql
  client/gql/dcis/mutations/document/change_document_comment.graphql
  client/gql/dcis/queries/document.graphql
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/documents.vue
  client/schema.graphql
  client/types/graphql.d.ts
  docs/docs/document_rules.md
  server/apps/dcis/migrations/0041_remove_document_comment.py
  server/apps/dcis/models/document.py
  server/apps/dcis/models/messages.py
  server/apps/dcis/permissions/__init__.py
  server/apps/dcis/permissions/document_permissions.py
  server/apps/dcis/schema/mutations/document_mutations.py
  server/apps/dcis/schema/types.py
  server/apps/dcis/services/add_document_data_services.py
  server/apps/dcis/services/document_services.py
  server/apps/dcis/tests/permissions/document_permissions.py
  server/apps/dcis/tests/services/document_services.py
Labels: enhancement, javascript, python

#1169 Пользователям разрешено локально менять ширину столбцов и высоту сток
  client/.eslintrc.js
  client/components/common/forms/MutationModalForm.vue
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridBody.vue
  client/components/dcis/grid/GridHeader.vue
  client/components/dcis/grid/controls/GridColumnControl.vue
  client/components/dcis/grid/controls/GridRowControl.vue
  client/components/dcis/grid/settings/GridChildRowSettings.vue
  client/components/dcis/grid/settings/GridColumnLocalSettings.vue
  client/components/dcis/grid/settings/GridColumnSettings.vue
  client/components/dcis/grid/settings/GridRowLocalSettings.vue
  client/components/dcis/grid/settings/GridRowSettings.vue
  client/composables/grid-actions.ts
  client/composables/grid-local-mutations.ts
  client/composables/grid-mutations.ts
  client/composables/grid-permissions.ts
  client/composables/grid-resizing.ts
  client/composables/grid.ts
  client/lang/ru/dcis.ts
Labels: feature, javascript

#1170 Уменьшен межстрочный интервал
  client/components/dcis/grid/Grid.vue
Labels: invalid, javascript

#1175 Поправлены стили для темной темы
  .github/dependabot.yml
  .github/lint_pull_request.yml
  .github/workflows/build.yml
  .github/workflows/docs.yml
  client/components/dcis/grid/Grid.vue
  client/components/dcis/grid/GridElementResizing.vue
  client/components/dcis/grid/GridSheetToolbar.vue
  client/components/dcis/grid/properties/AggregationProperty.vue
  client/composables/query-relay.ts
  client/lang/ru/dcis.ts
  client/pages/dcis/periods/_periodId/limitations.vue
  client/pages/panel/ac/curator_groups.vue
  client/pages/panel/ac/groups.vue
  client/pages/profile/files.vue
Labels: bug, javascript
